# Free format
# Do not alter the first (cmd <- ') and last (') components of the command
# For many parameters, if NULL, default will be used!

cmd <-'
title        ="Ubiquitin_example",
pdbname      ="example.pdb",
pdbtype      ="almost",
seqshift     =0,
examine      =0,
experdata    ="example.exp",
rereference  =FALSE,
outputname   ="out.txt",
outorder     ="byseq",
bias         =2,
noconstraints=NULL,
saveplot     =TRUE,
plotheight   =550,
plotwidth    =550,
pointlabel   =TRUE,
linelabel    =TRUE,
plotname     ="hsqc.jpg",
colALA       =NULL,
colVAL       =NULL,
colLEU       =NULL,
colILE       =NULL,
colTHR       =NULL,
colMET       =NULL,
plotexper    =TRUE,
expCOL       =NULL,
colALAexp    =NULL,
colVALexp    =NULL,
colTHRexp    =NULL,
colLEUexp    =NULL,
colILEexp    =NULL,
colMETexp    =NULL,
xlim         =NULL,
ylim         =NULL,
viewplot     =FALSE,
zooming      =FALSE,
interactive  =FALSE,
Cmargin      =NULL,
Hmargin      =NULL,
default.csCrange=NULL,
default.csHrange=NULL,
minRerefNum  =NULL,
cex1=NULL, lwd1=NULL,
cex2=NULL, lwd2=NULL,
cex3=NULL, lwd3=NULL
'
